server:
  port: ${SERVER_PORT:8090}
spring:
  thymeleaf:
    cache: true
  devtools:
    restart:
        enabled: true #设置开启热部署
  freemarker:
    cache: false #页面不加载缓存，修改即时生效
  mybatis: 
    typeAliasesPackage: com.wzzzzor.billrecord.domain
    mapperLocations: classpath:mapper/*.xml
    dialect: oracle
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@${JDBC_URL:101.231.81.202:9521:dev}
    username: ${JDBC_USERNAME:platform_portal}
    password: ${JDBC_PASSWORD:kingstar}
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 6000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    filters: stat,wall,log4j
    logSlowSql: true
  redis: 
    host: ${REDIS_HOST:192.168.1.138}
    port: ${REDIS_PORT:6379}
    # password: ${REDIS_PASSWORD:}
logging:
  path: ${LOGGING_PATH:}