server:
  port: 8090
spring: 
  devtools:
    restart:
        enabled: true #设置开启热部署
  freemarker:
    cache: false #页面不加载缓存，修改即时生效
  mybatis: 
    typeAliasesPackage: com.wzzzzor.billrecord.domain
    mapperLocations: classpath:mapper/*.xml
    dialect: oracle
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.1.190:1521:dev
    username: platform_portal
    password: kingstar
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 6000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    filters: stat,wall,log4j
    logSlowSql: true